// Generate the rootless Quadlet `.kube` unit that makes systemd own a pod.
//
// Dropped in ~/.config/containers/systemd/<pod>.kube next to <pod>.yaml, the
// systemd generator turns it into <pod>.service. With linger enabled the user
// manager starts it on boot — this is v3's reboot survival (SPEC-v3.md).

export function kubeUnit(podName: string): string {
  return `# Generated by vz apply — do not edit by hand.
[Unit]
Description=vz pod ${podName}

[Kube]
Yaml=${podName}.yaml

[Install]
WantedBy=default.target
`;
}

// The systemd service name Quadlet generates from <pod>.kube.
export function serviceName(podName: string): string {
  return `${podName}.service`;
}
