/bin
/dev
/etc/gai.conf
/etc/gearmand.conf
/etc/resolv.conf
/lib
/mnt
/opt
/proc
/run
/sbin
/srv
/sys
/tmp
/usr/bin/gearmand
/usr/lib/ld-2.23.so
/usr/lib/ld-linux.so.2
/usr/lib/libboost_program_options.so.1.60.0
/usr/lib/libc-2.23.so
/usr/lib/libc.so.6
/usr/lib/libcom_err.so.2
/usr/lib/libcom_err.so.2.1
/usr/lib/libcrypto.so.1.0.0
/usr/lib/libdl-2.23.so
/usr/lib/libdl.so.2
/usr/lib/libevent-2.0.so.5
/usr/lib/libevent-2.0.so.5.1.10
/usr/lib/libgcc_s.so.1
/usr/lib/libgssapi_krb5.so.2
/usr/lib/libgssapi_krb5.so.2.2
/usr/lib/libhiredis.so.0.13
/usr/lib/libk5crypto.so.3
/usr/lib/libk5crypto.so.3.1
/usr/lib/libkeyutils.so.1
/usr/lib/libkeyutils.so.1.5
/usr/lib/libkrb5.so.3
/usr/lib/libkrb5.so.3.3
/usr/lib/libkrb5support.so.0
/usr/lib/libkrb5support.so.0.1
/usr/lib/libm-2.23.so
/usr/lib/libm.so.6
/usr/lib/libmysqlclient.so.18
/usr/lib/libmysqlclient.so.18.0.0
/usr/lib/libpq.so.5
/usr/lib/libpq.so.5.8
/usr/lib/libpthread-2.23.so
/usr/lib/libpthread.so.0
/usr/lib/libresolv-2.23.so
/usr/lib/libresolv.so.2
/usr/lib/librt-2.23.so
/usr/lib/librt.so.1
/usr/lib/libsqlite3.so.0
/usr/lib/libsqlite3.so.0.8.6
/usr/lib/libssl.so.1.0.0
/usr/lib/libstdc++.so.6
/usr/lib/libstdc++.so.6.0.21
/usr/lib/libz.so.1
/usr/lib/libz.so.1.2.8
/usr/sbin
