---
- name: reload nftables
  ansible.builtin.systemd_service:
    name: nftables
    state: reloaded

- name: restart dnsmasq
  ansible.builtin.systemd_service:
    name: dnsmasq
    state: restarted
